services:
  # ── API Node.js ─────────────────────────────────
  - type: web
    name: mam-buudu-api
    env: node
    region: frankfurt          # plus proche de l'Afrique de l'Ouest que Oregon
    plan: free
    buildCommand: npm install --include=dev && npm run prisma:generate && npm run build && DATABASE_URL="$DIRECT_URL" npm run prisma:migrate:deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://postgres.phgfzrhdqixwdbcaojvi:Admin_postgres_supabase@aws-0-eu-west-1.pooler.supabase.com:5432/postgres?pgbouncer=true&sslmode=require"
      - key: DIRECT_URL
        value: "postgresql://postgres.phgfzrhdqixwdbcaojvi:Admin_postgres_supabase@aws-0-eu-west-1.pooler.supabase.co:5432/postgres?sslmode=require"
      - key: JWT_SECRET
        # generateValue: true  
        value: c53e2706e5d84f2cab96d60d7437aae4  # Render génère une valeur aléatoire automatiquement
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: API_BASE_URL
        value: https://mam-buudu-api.onrender.com
      - key: CORS_ORIGIN
        value: https://mam-buudu-web.netlify.app, https://V_1--mambuudu.netlify.app, http://localhost:4200, http://localhost:4202

# Transaction pooler - pour l'application
DATABASE_URL="postgresql://postgres.faguokbovbwlgstbjohy:MamanSabine1982@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true&sslmode=requi

 # ── API Node.js ─────────────────────────────────
  # ── API Node.js ─────────────────────────────────
  # ── API Node.js ─────────────────────────────────
  # ── API Node.js ─────────────────────────────────
  # ── API Node.js ───────────────────────────────── VERSION RENDER DB

# services:
#   - type: web
#     name: mam-buudu-api
#     env: node
#     region: frankfurt          # plus proche de l'Afrique de l'Ouest que Oregon
#     plan: free
#     buildCommand: npm install && npm run prisma:generate && npm run build && npm run prisma:migrate:deploy
#     startCommand: npm start
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: DATABASE_URL
#         fromDatabase:
#           name: mam-buudu-db
#           property: connectionString
#       - key: JWT_SECRET
#         generateValue: true    # Render génère une valeur aléatoire automatiquement
#       - key: JWT_EXPIRES_IN
#         value: 30d
#       - key: API_BASE_URL
#         value: https://mam-buudu-api.onrender.com

# databases:
#   - name: mam-buudu-db
#     databaseName: mam_buudu
#     user: mam_buudu_user
#     plan: free
#     region: frankfurt
